import pandas as pd

def add_technical_indicators(df):
    """
    Adds basic technical indicators to the historical dataset.
    Users can extend this function to include MACD, Bollinger Bands, etc.
    """
    df = df.copy()
    
    # Simple Moving Averages (SMA)
    if len(df) >= 10:
        df['SMA_10'] = df['Close'].rolling(window=10).mean()
    if len(df) >= 20:
        df['SMA_20'] = df['Close'].rolling(window=20).mean()
        
    # Relative Strength Index (RSI) - 14 Days
    delta = df['Close'].diff(1)
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)
    avg_gain = gain.rolling(window=14).mean()
    avg_loss = loss.rolling(window=14).mean()
    
    rs = avg_gain / avg_loss
    df['RSI_14'] = 100 - (100 / (1 + rs))
    
    # Fill NaN values generated by rolling calculations
    df.fillna(method='bfill', inplace=True)
    
    return df

def load_and_preprocess_data(file_path):
    """
    Loads data from CSV, sets DateTime index, and adds indicators.
    """
    print(f"Loading data from: {file_path}")
    df = pd.read_csv(file_path)
    if 'Date' in df.columns:
        df['Date'] = pd.to_datetime(df['Date'])
        df.set_index('Date', inplace=True)
    
    df = add_technical_indicators(df)
    return df
